apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-app.fullname" . }}
  labels:
    {{- include "devops-app.labels" . | nindent 4 }}
spec:
  # ClusterIP: Internal virtual IP accessible only within the cluster
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  # Magnet (Selector): Routes incoming requests to matching pods
  selector:
    {{- include "devops-app.selectorLabels" . | nindent 4 }}
