apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-app-prod
  namespace: argocd
spec:
  project: default
  # 1. Source: Points to charts directory with values-prod.yaml
  source:
    repoURL: https://github.com/erendemirer1/cloud-native-devops-platform.git
    targetRevision: HEAD
    path: charts
    helm:
      valueFiles:
        - values-prod.yaml

  # 2. Destination: Deploy to prod namespace
  destination:
    server: https://kubernetes.default.svc
    namespace: prod

  # 3. Automated GitOps and Self-Healing
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
