apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-app-dev
  namespace: argocd
spec:
  project: default
  # 1. Source: Where is the code located in Git?
  source:
    repoURL: https://github.com/erendemirer1/Production-GitOps-Engine.git
    targetRevision: HEAD
    path: charts
    helm:
      valueFiles:
        - values-dev.yaml

  # 2. Destination: Where to deploy inside Kubernetes?
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  # 3. Sync Policy: Full automated GitOps and Self-Healing
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
